config = {'train_data_path':['/media/arjun/Data/doc-data/LUNA16',],
          'val_data_path':['/media/arjun/Data/doc-data/subset0/'], 
          'test_data_path': ['/media/arjun/Data/doc-data/subset0/'], 
          
          'train_preprocess_result_path':'/media/arjun/Data/doc-data/pre-processed/', # contains numpy for the data and label, which is generated by prepare.py
          'val_preprocess_result_path':'/media/arjun/Data/doc-data/pre-processed/',  # make sure copy all the numpy into one folder after prepare.py
          'test_preprocess_result_path':'/media/arjun/Data/doc-data/pre-processed/',
          
          'train_annos_path':'/media/arjun/Data/doc-data/LUNA16/annotations.csv',
          'val_annos_path': '/media/arjun/Data/doc-data/LUNA16/annotations.csv',
          'test_annos_path': '/media/arjun/Data/doc-data/LUNA16/annotations.csv',

          'black_list':[],
          
          'preprocessing_backend':'python3',

          'luna_segment':'/media/arjun/Data/doc-data/LUNA16/seg-lungs-LUNA16/', # download from https://luna16.grand-challenge.org/data/
          'preprocess_result_path':'/media/arjun/Data/doc-data/LUNA16/annotations.csv/pre-processed/',
          'luna_data':'/media/arjun/Data/doc-data/LUNA16/',
          'luna_label':'/media/arjun/Data/doc-data/LUNA16/annotations.csv'
         } 
